### ISSUE TITLE
does not work on Robin Nano V2 card

### ISSUE THREAD

**Issue by FabioMiranda10** [makerbase-mks/MKS-WIFI#10]
I just received my Robin Nano V2 card, but it is not updating the MksWifi.bin file. 
How to make?
I updated the firmware and don't read the .bin file

![foto](https://user-images.githubusercontent.com/72291863/94984007-0ec6cf00-051e-11eb-94bf-a645b64d2d5c.jpeg)

**Comment by makerbase-mks** [comment]
Hi! This feature is under development

**Comment by mks-viva** [comment]
@FabioMiranda10 
The latest version firmware has supported wifi function, you can refer to it: https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware
