### ISSUE TITLE
MKS Wifi with ESP3D Firmware do not communicate with MKS Robin Nano 

### ISSUE THREAD

**Issue by easycorexy** [makerbase-mks/MKS-WIFI#11]
Hello,

i have installed the ESP3D Firmware on the MKS Wifi Module. The firmware works fine and the WebUi also is also ok.

I have the following problem: **The Wifi-module doesn't communicate with the motherboard.**

I have MKS_Robin_Nano_V1.2 Board with Mks-Robin-Nano-Marlin2.0-Firmware on it.

Can you help telling me what do have to do to make this work?

Thanks in advance

**Comment by mks-viva** [comment]
You need setting #define SERIAL_PORT_2 1, because Robin wifi interface usart is STM32 PA9,PA10 and it is Usart1

**Comment by mks-viva** [comment]
@easycorexy 
You need setting #define SERIAL_PORT_2 1, because Robin wifi interface usart is STM32 PA9,PA10 and it is Usart1

**Comment by mks-viva** [comment]
I will close this issues temporatity.
