### ISSUE TITLE
Board MKS Robin Nano V 1.x WiFi don't Work

### ISSUE THREAD

**Issue by Bighoneypot** [makerbase-mks/MKS-WIFI#16]
Good Morning, yestarday I have installed into my MKS Robin Nano V 1.x new Firmware version Marlin- bugfix2.0.x - MKS 2.1.2, but wifi don't work.
I have upgrade WiFi firmware with last version, but wifi don't Work https://github.com/makerbase-mks/MKS-WIFI

I have a question, about this problem.
There is a solution to fix this problem?
Also, can you hel me to downgrade firmware with a stable build??

I use Board MKS Robin Nano V 1.x with Ender 3 PRO.

![Inked20210116_121254_HDR_LI](https://user-images.githubusercontent.com/35570068/104811101-81bc3300-57f9-11eb-94a2-6c0f05604df6.jpg)
![Inked20210116_121230_LI](https://user-images.githubusercontent.com/35570068/104811110-926ca900-57f9-11eb-889c-a4bc0efea8ab.jpg)

**Comment by Bighoneypot** [comment]
I have try this https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/tree/master/Nano%20firmware%20Marlin 

and for me work fine!!!

**Comment by Bighoneypot** [comment]
I have try this https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/tree/master/Nano%20firmware%20Marlin 

and for me work fine.

But I need to mod source File

**Comment by RicPaiva** [comment]
Hi @Bighoneypot, 
I´m facing the same issue with Marlin- bugfix2.0.x - MKS 2.1.3.
You said you had to mod source file...
Do you have any idea how to solve it.
Thanks in advance...
