### ISSUE TITLE
STA Disconnected (Robin nano / MKS WiFi / Sapphire pro)

### ISSUE THREAD

**Issue by Sergey-Afonin** [makerbase-mks/MKS-WIFI#5]
I put DIY module based on ESP12F to Robin nano and upgraded firmware.
I can  see IP address of printer on screen (obtained via DHCP) and Wifi name, but status is STA Disconnected. Meanwhile I can ping it from the network and can communicate with it's configuration screen via web page. I know one more person with the same issue. We used MKS formware and TwoTrees fork. Both versions do the same and have the same behevoiur and messages.
What can be wrong here?
![IMG_20200522_154103](https://user-images.githubusercontent.com/20800871/82814390-c2002700-9e9f-11ea-939d-4c3c7176072d.jpg)
![Сохраненное изображение 2020-5-22_15-52-42 573](https://user-images.githubusercontent.com/20800871/82814435-db08d800-9e9f-11ea-974c-8f8dba34e2c6.jpg)
![Сохраненное изображение 2020-5-22_15-52-59 152](https://user-images.githubusercontent.com/20800871/82814441-de9c5f00-9e9f-11ea-85cc-c91fc25aff91.jpg)

**Comment by Sergey-Afonin** [comment]
Thank you! I'll do own job to resolve.

**Comment by Onegin45** [comment]
Сергей, здравствуйте. Имею подобную проблему, с той лишь разницей, что принтер ip и символ облака на своем экране не показывает показывает. Вебсайт с зеленым фоном тоже доступен. Слайсер принтера не видит. Вы как-то победили эту проблему?

**Comment by Sergey-Afonin** [comment]
> Сергей, здравствуйте. Имею подобную проблему, с той лишь разницей, что принтер ip и символ облака на своем экране не показывает. Вебсайт с зеленым фоном тоже доступен. Слайсер принтера не видит. Вы как-то победили эту проблему?

Я купил готовый модуль вместо самодельного. Понимаю, что здесь описано не всё. Только прошивки не хватает. Нужно как-то еще настроить модуль.

**Comment by Onegin45** [comment]
Извините, что поздно. Если модуль покупной, то все должно работать из
коробки. Если вебсайт доступен, то модуль исправен и видит сеть. Смотрите в
настройках слайсера. У меня принтер в Куре периодически теряется - помогает
удалить\настроить заново подключение по Wifi

вс, 12 июл. 2020 г. в 19:55, Sergey-Afonin ***@***.***>:
